apiVersion: apps/v1
kind: Deployment
metadata:
  name: quartz-job
  namespace: dash0-dotnet-examples
  labels:
    app: quartz-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quartz-job
  template:
    metadata:
      labels:
        app: quartz-job
    spec:
      containers:
        - name: quartz-job
          image: localhost:5001/dash0-dotnet-example-quartz-job:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quartz-job
  namespace: dash0-dotnet-examples
spec:
  selector:
    app: quartz-job
  ports:
    - port: 8080
      targetPort: 8080
